# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02e57946331460edcd02e6694e09a59d02288c1861de193c5adab02b43dd50622bcc0a94f838a1b730470c765f47084ccf67edf5ce15254a340ed3c5d2531f83

test:
  secret_key_base: e2bc801007b627c476a0e3833ea241a243db53969a3f75e9199d507b39ebd84a6e1ed6b0c1d0860f02f40da2d85de1219491c844914112853c5a3bfaa32df0d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
